from unicodedata import name
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('home/', views.home, name="home"),
    path('', views.redirectLogin, name="redirectLogin"),
    path('creatt/', views.index),
    path('home/apply-job', views.applyJob, name="applyJob"),
    path('job-search/', views.jobSearch, name="jobSearch"),
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('login-process/', views.loginProcess, name="loginProcess"),
    path('logout/', views.logout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('profile/seeker-edit-profile', views.seekerEdit, name="seekerEdit"),
    path('profile/seeker-delete-account',
         views.seekerDeleteAccount, name="seekerDeleteAccount"),
    path('profile/seeker-change-profile',
         views.seekerChangeProfle, name="seekerChangeProfle"),
    path('profile/seeker-change-password',
         views.seekerChangePassword, name="seekerChangePassword"),
    path('seeker-resume/', views.seekerView, name="seekerView"),
    path('profile/seeker-edit-process',
         views.seekerEditProcess, name="seekerEditProcess"),
    path('profile/provider-change-profile',
         views.providerChangeProfle, name="providerChangeProfle"),
    path('profile/provider-delete-account',
         views.providerDeleteAccount, name="providerDeleteAccount"),
    path('profile/provider-change-password',
         views.providerChangePassword, name="providerChangePassword"),
    path('profile/provider-edit-profile',
         views.providerEdit, name="providerEdit"),
    path('profile/provider-edit-process',
         views.providerEditProcess, name="providerEditProcess"),
    path('profile/provider-add-job', views.providerAddJob, name="providerAddJob"),
    path('profile/provider-add-job-process',
         views.providerAddJobProcess, name="providerAddJobProcess"),
    path('profile/view-post/', views.providerViewPost, name="providerViewPost"),
    path('profile/view-applicant', views.providerViewApplicant,
         name="providerViewApplicant"),
    path('profile/view-applicant-resume', views.providerViewApplicantResume,
         name="providerViewApplicantResume"),
    path('home/view-post/', views.indexViewPost, name="indexViewPost"),
    path('profile/provider-edit-job',
         views.providerEditJob, name="providerEditJob"),
    path('profile/provider-deactivate-job',
         views.providerDeactivateJob, name="providerDeactivateJob"),
    path('profile/provider-activate-job',
         views.providerActivateJob, name="providerActivateJob"),
    path('profile/provider-edit-job-process',
         views.providerEditJobProcess, name="providerEditJobProcess"),
    path('manage_user/', views.manage_user, name="manage_user"),
    path('admin-login/', views.admin_login, name="admin_login"),
    path('admin-logout/', views.admin_logout, name="admin_logout"),
    path('admin-login-process/', views.admin_login_process, name="admin_login_process"),
    path('manage_user/activate_user',views.admin_activate_user, name="admin_activate_user"),
    path('manage_user/deactivate_user',views.admin_deactivate_user, name="admin_deactivate_user"),
    path('admin-edit-user/', views.admin_edit_user, name="admin-edit-user"),
    path('admin-edit-user-process/', views.admin_edit_user_process,name="admin-edit-user-process"),
    path('company/', views.company, name="company"),
    path('admin-edit-company/', views.admin_edit_company,name="admin-edit-company"),
    path('admin-edit-company-process/', views.admin_edit_company_process,name="admin-edit-company-process"),
    path('company/activate_company', views.admin_activate_company,name="admin_deactivate_company"),
    path('company/deactivate_company', views.admin_deactivate_company,name="admin_activate_company"),
    path('jobs/', views.jobs, name="jobs"),
    path('admin-edit-job/', views.admin_edit_job,name="admin-edit-job"),
    path('admin-edit-job-process/', views.admin_edit_job_process,name="admin-edit-job-process"),
    path('jobs/activate_job', views.admin_activate_jobs,name="admin_activate_jobs"),
    path('jobs/deactivate_job', views.admin_deactivate_jobs,name="admin_deactivate_jobs"),
    path('activity_logs/', views.activity_logs, name="activity_logs"),
    path('users-report/', views.users_report, name="users_report"),
    path('activity-report/', views.activity_report, name="activity_report"),
    path('job-report/', views.job_report, name="job_report"),
    path('company-report/', views.company_report, name="company_report"),
]
