# Generated by Django 3.2.11 on 2022-02-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0009_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(null=True, upload_to='C:\\Users\\Mohammed\\Documents\\Job_Portal_Git\\django-webproject\\media'),
        ),
    ]
