# Generated by Django 3.2.11 on 2022-02-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0010_auto_20220213_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
