# Generated by Django 3.2.11 on 2022-02-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0011_job_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user_id',
        ),
    ]
