# Generated by Django 4.0.1 on 2022-02-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0012_remove_job_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROFILE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('profile', models.FileField(null=True, upload_to='D:\\Xampp\\htdocs\\django-webproject\\media')),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(null=True, upload_to='D:\\Xampp\\htdocs\\django-webproject\\media'),
        ),
    ]
